About/urls.py
from django.urls import path
from .views import about, create_testimoni

app_name = 'About'
urlpatterns = [
 path('', about, name='about'),
 path('create-testimoni/', create_testimoni, name='create-testimoni'),
]

Donate/urls.py
from django.urls import path
from .views import showDonationForm, submitDonation, cekDonasi

app_name = 'Donate'
urlpatterns = [
    path('', showDonationForm, name='donasi'),
    path('submit-donation/', submitDonation, name='submit-donation'),
    path('cek-donasi/', cekDonasi, name='cek-donasi'),
]

Homepage/urls.py
from django.urls import path
from .views import *

app_name = 'Homepage'
urlpatterns = [
    path('', index, name='index'),
]

News/urls.py
from django.urls import path
from .views import showNews

app_name = 'News'
urlpatterns = [
 path('', showNews, name='news')
]

Register/urls.py
from django.urls import path
from .views import showRegisterForm, submitRegistration, login, logout, yourProfile

app_name = 'Register'
urlpatterns = [
    path('', showRegisterForm, name='register'),
    path('submit-registration', submitRegistration, name='submit-registration'),
    path('logout', logout, name='logout'),
    path('login', login, name='login'),
    path('yourProfile', yourProfile, name='yourProfile'),
]

daftardonasi/urls.py
from django.urls import path
from daftardonasi.views import *

app_name = "daftardonasi"
urlpatterns = [
    path('', DaftarDonasi, name='daftardonasi'),
    path('ListDonasi/', ListDonasi, name='ListDonasi'),
]

kita_sabi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
import Homepage.urls as Homepage
import News.urls as News
import Register.urls as Register
import Donate.urls as Donate
import About.urls as About
import daftardonasi.urls as daftardonasi
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='Home')),
    path('Home', include(Homepage), name="Home"),
    path('News', include(News)),
    path('Register', include(Register)),
    path('Donate/', include(Donate)),
    path('About/', include(About)),
    path('daftardonasi/', include(daftardonasi)),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Homepage/models.py
from django.db import models

# Create your models here.


class Donatur(models.Model):
    nama = models.CharField(max_length=30)
    jumlah = models.IntegerField()


    def __str__(self):
        return self.nama

class DisastersModels(models.Model):
    HIGHLIGHT = 'Highlight'
    CARD = 'Card'
    HIGHLIGHT_CARD_CHOICES = (
        (HIGHLIGHT, 'Highlight'),
        (CARD, 'Card'),
    )
    DisasterImage = models.URLField(max_length = 500)
    DisasterName = models.CharField(max_length = 30)
    DisasterDesc = models.TextField(max_length= 150)
    HighlightOrCard = models.CharField(max_length = 10, choices = HIGHLIGHT_CARD_CHOICES)
    donaturs = models.ManyToManyField(Donatur, blank=True)
    SumOfDonation = models.IntegerField(blank=True, null=True)


    def __str__(self):
        return self.DisasterName

    class Meta:
        ordering=['-HighlightOrCard']



    



    

Homepage/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .models import DisastersModels

# Create your views here.

def index(request):
    HighlightDisaster = DisastersModels.objects.filter(HighlightOrCard = "Highlight")
    CardDisaster = DisastersModels.objects.filter(HighlightOrCard = "Card")
    FirstHighlight = DisastersModels.objects.filter(HighlightOrCard = "Highlight").first()
    response = {"HighlightDisaster" : HighlightDisaster, "CardDisaster" : CardDisaster, "FirstHighlight" : FirstHighlight}
    return render(request, 'index.html', response)

    

Homepage/templates/partials/footer.html
<p>&copy; KitaSabi | 2018</p>

Homepage/templates/partials/header.html
{% load static %}
<nav id="header" class="navbar navbar-expand-lg navbar-dark" style="background-image: linear-gradient(to right, #0A9D4C, #11ac3c)">
    <a class="navbar-brand" href="{% url 'Homepage:index' %}"><img width="220" src="{% static 'img/Brand.png' %}"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Donate:donasi' %}">Donasi <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'daftardonasi:daftardonasi' %}">Daftar Donasi<span class="sr-only">(current)</span></a>
                </li>
            {% endif %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'News:news' %}">Berita <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a id="about" class="nav-link" href="{% url 'About:about' %}">Tentang Kami <span class="sr-only">(current)</span></a>
            </li>
            
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" onclick='signOut()'>Sign out <span class="sr-only">(current)</span></a>
                </li>
                
            {% else %}
                <li class="nav-item active" id="regisWrapper">
                    <a id="registrasi" class="nav-link" href="{% url 'Register:register' %}">Registrasi <span class="sr-only">(current)</span></a>
                </li>
            {% endif %}
            
        </ul>
    </div>
</nav>

<meta charset="UTF-8">
<meta name="google-signin-client_id" content="706201221112-pm1bbjno6mqki3d8tu6pv1gi1aepmf1c.apps.googleusercontent.com">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="google-signin-scope" content="profile email">
<script src="https://apis.google.com/js/platform.js" ></script>
<script type="text/javascript">
    function onSignIn(googleUser) {
            var profile = googleUser.getBasicProfile();
            var id_token = googleUser.getAuthResponse().id_token;
            $.ajax({
                method: "POST",
                type: "POST",
                url: "/Registerlogin",
                headers: {
                    "X-CSRFToken": document.getElementsByName('csrfmiddlewaretoken')[0].value
                },
                data: {
                    token: id_token
                },
                
                success: function(result) {
                    if (result['status'] == "0") {
                        approved(profile);
                        console.log(profile.getName());
                    } else {
                        console.log(result);
                        alert("G(et)T(he)F(un)O(ut), BEACH!!!");
                    }
                }
            })
        };

    function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function() {
            console.log('User signed out.');
        });
        window.location.href = "{% url 'Register:logout' %}"
    }


    function approved(profile) {
        var id = profile.getId();
        var name = profile.getName();
        var givenName = profile.getGivenName();
        var emailUrl = profile.getEmail();
        var avatar = profile.getImageUrl();

        var paramsToSend = {
            'id': id,
            'name': name,
            'givenName': givenName,
            'emailUrl': emailUrl,
            'avatar': avatar,
            'csrfmiddlewaretoken': document.getElementsByName('csrfmiddlewaretoken')[0].value
        }

        var form = document.createElement("form");
        form.setAttribute("method", "POST");
        form.setAttribute("action", "{% url 'Register:yourProfile' %}");

        for (var key in paramsToSend) {
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", key);
            hiddenField.setAttribute("value", paramsToSend[key]);
            form.appendChild(hiddenField);
        }
        document.body.appendChild(form);

        form.submit()
    }
    $(document).ready(function() {
        gapi.load('auth2', function() {
            gapi.auth2.init();
        });
    });
    
    

</script>

Homepage/templates/partials/source.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
<link href="{% static 'css/base.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/header.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/footer.css'%}" rel="stylesheet" type="text/css">

<script src="https://code.jquery.com/jquery-3.3.1.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>