News/urls.py
from django.urls import path
from .views import showNews

app_name = 'News'
urlpatterns = [
 path('', showNews, name='news')
]

Register/urls.py
from django.urls import path
from .views import showRegisterForm, submitRegistration, login, logout, yourProfile

app_name = 'Register'
urlpatterns = [
    path('', showRegisterForm, name='register'),
    path('submit-registration', submitRegistration, name='submit-registration'),
    path('logout', logout, name='logout'),
    path('login', login, name='login'),
    path('yourProfile', yourProfile, name='yourProfile'),
]

kita_sabi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
import Homepage.urls as Homepage
import News.urls as News
import Register.urls as Register
import Donate.urls as Donate
import About.urls as About
import daftardonasi.urls as daftardonasi
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='Home')),
    path('Home', include(Homepage), name="Home"),
    path('News', include(News)),
    path('Register', include(Register)),
    path('Donate/', include(Donate)),
    path('About/', include(About)),
    path('daftardonasi/', include(daftardonasi)),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Register/models.py
from django.db import models
from django.utils import timezone

class reg(models.Model):
    name = models.CharField(max_length = 30)
    birthdate = models.DateField(max_length = 30, default = timezone.now)
    email = models.EmailField(max_length = 30)
    password = models.CharField(max_length = 30)

Register/forms.py
from django import forms

class regForm(forms.Form):
    attrsName = {
        'class' : 'form-control',
        'placeholder' : 'Nama Lengkap'
    }
    
    attrsBirthdate = {
        'class' : 'form-control',
        'type' : 'date',
        'placeholder' : 'Tanggal Lahir'
    }
    
    attrsEmail = {
        'class' : 'form-control',
        'placeholder' : 'Email'
    }
    
    attrsPassword = {
        'class' : 'form-control',
        'placeholder' : 'Sandi'
    }
    
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs=attrsName), required = True, label = "")
    birthdate = forms.DateField(widget=forms.DateInput(attrs=attrsBirthdate), required = True, label = "")
    email = forms.EmailField(max_length = 30, widget=forms.EmailInput(attrs=attrsEmail), required = True, label = "")
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs=attrsPassword), required = True, label = "")

Register/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import google
from google.oauth2 import id_token
from google.auth.transport import requests as request2
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import logout as lout
from django.contrib.auth import login as lin

from .forms import regForm
from .models import reg

response = {'author' : 'Bagus Pribadi'}
def showRegisterForm(request):
    regs = reg.objects.all()
    form = regForm(request.POST)
    context = {
        'form' : form,
    }
    return render(request, 'register.html', context)
    
def submitRegistration(request):
    if request.method == 'POST':
        form = regForm(request.POST)
        response['name'] = request.POST['name']
        response['birthdate'] = request.POST['birthdate']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        re = reg(name = response['name'], birthdate = response['birthdate'], email = response['email'], password = response['password'])
        re.save()
        form = regForm()
        return HttpResponseRedirect(reverse('Register:register'))
    else:
        form = regForm()
        regs = reg.objects.all()
        context = {
            'form': form,
            'regs': regs
        }
        return render(request, 'register.html', context)
        
def login(request):
    if (request.method == "POST"):
        response = {
            'status' : "0"
        }
        try:
            toVerify = request.POST['token']
            info = id_token.verify_oauth2_token(toVerify, request2.Request(),"706201221112-pm1bbjno6mqki3d8tu6pv1gi1aepmf1c.apps.googleusercontent.com")
            if (info['iss'] not in ['accounts.google.com', 'https://accounts.google.com']):
                raise ValueError('Wrong issuer.')
            return JsonResponse(response)
        except ValueError:
            response["status"] = "1"
    return JsonResponse({'error': request.method})
    
def logout(request):
    request.session.flush()
    lout(request)
    return HttpResponseRedirect(reverse('Register:register'))
    
def yourProfile(request):
    if request.method == "POST":
        try:
            userid = request.POST['id']
            email = request.POST['emailUrl']
            name = request.POST['name']
            request.session['user_id'] = userid
            request.session['emailUrl'] = email
            request.session['name'] = name
        except ValueError:
            return JsonResponse({"status": "1"})
    if not (User.objects.filter(email=request.POST['emailUrl']).exists()):
        user = User.objects.create_user(username=request.POST["name"], email=request.POST["emailUrl"])
        user.save()
        lin(request, user)
    else:
        user = User.objects.get(email=request.POST['emailUrl'])
        user.save()
        lin(request, user)
    return HttpResponseRedirect(reverse('Homepage:index'))

Register/templates/register.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}
    Register
{% endblock title %}

{% block css %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
    <meta name="google-signin-client_id" content="706201221112-pm1bbjno6mqki3d8tu6pv1gi1aepmf1c.apps.googleusercontent.com">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-signin-scope" content="profile email">
    <script src="https://apis.google.com/js/platform.js" ></script>
{% endblock css %}

{% block content %}
    <div class="container mx-auto d-block">
        <form class="form-block" action="{% url 'Register:submit-registration' %}" method="POST">
            <h3 style="color: #0A9D4C">Mari registrasi untuk donasi!</h3>
            {% csrf_token %}
            <div class="form-group">
                {% for field in form %}
                    {% if field.name == 'anonymous' %}
                        {{ field.as_widget }} <label>{{ field.label }}</label>
                        {% else %}
                        {{ field.as_widget }}
                    {% endif %}
                {% endfor %}
            </div>
            <button type="submit" class="btn">Daftar</button>
            <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
            <!-- <div class="signout"><a onclick="signOut()">Sign out</a></div> -->
        </form>
    </div>
    
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
    <script type="text/javascript">
    function onSignIn(googleUser) {
        var profile = googleUser.getBasicProfile();
        var id_token = googleUser.getAuthResponse().id_token;
        $.ajax({
            method: "POST",
            type: "POST",
            url: "/Registerlogin",
            headers: {
                "X-CSRFToken": document.getElementsByName('csrfmiddlewaretoken')[0].value
            },
            data: {
                token: id_token
            },
            
            success: function(result) {
                if (result['status'] == "0") {
                    approved(profile);
                    console.log(profile.getName());
                } else {
                    console.log(result);
                    alert("G(et)T(he)F(un)O(ut), BEACH!!!");
                }
            }
        })
    };

    function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function() {
            console.log('User signed out.');
        });
        window.location.href = "{% url 'Register:logout' %}"
    }


    function approved(profile) {
        var id = profile.getId();
        var name = profile.getName();
        var givenName = profile.getGivenName();
        var emailUrl = profile.getEmail();
        var avatar = profile.getImageUrl();

        var paramsToSend = {
            'id': id,
            'name': name,
            'givenName': givenName,
            'emailUrl': emailUrl,
            'avatar': avatar,
            'csrfmiddlewaretoken': document.getElementsByName('csrfmiddlewaretoken')[0].value
        }

        var form = document.createElement("form");
        form.setAttribute("method", "POST");
        form.setAttribute("action", "{% url 'Register:yourProfile' %}");

        for (var key in paramsToSend) {
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", key);
            hiddenField.setAttribute("value", paramsToSend[key]);
            form.appendChild(hiddenField);
        }
        document.body.appendChild(form);

        form.submit()
    }
    
    $(document).ready(function() {
        gapi.load('auth2', function() {
            gapi.auth2.init();
        });
    });
    </script>
    
{% endblock content %}