News/urls.py
from django.urls import path
from .views import showNews

app_name = 'News'
urlpatterns = [
 path('', showNews, name='news')
]

daftardonasi/urls.py
from django.urls import path
from daftardonasi.views import *

app_name = "daftardonasi"
urlpatterns = [
    path('', DaftarDonasi, name='daftardonasi'),
    path('ListDonasi/', ListDonasi, name='ListDonasi'),
]

kita_sabi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
import Homepage.urls as Homepage
import News.urls as News
import Register.urls as Register
import Donate.urls as Donate
import About.urls as About
import daftardonasi.urls as daftardonasi
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='Home')),
    path('Home', include(Homepage), name="Home"),
    path('News', include(News)),
    path('Register', include(Register)),
    path('Donate/', include(Donate)),
    path('About/', include(About)),
    path('daftardonasi/', include(daftardonasi)),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daftardonasi/models.py
from django.db import models

# Create your models here.

daftardonasi/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from Donate.models import Donasi
from django.http import JsonResponse
import json
from Donate.models import Donasi

# Create your views here.

def DaftarDonasi(request):
    return render(request, 'daftardonasi.html')

# @login_required
def ListDonasi(request):
    if request.method == "GET":
        # name = request.session["userGivenName"]
        # data = list(Donasi.objects.filter(nama=name).values())
        email = request.user.email
        ListDonasi = Donasi.objects.filter(email=email)
        data = []
        for donasi in ListDonasi:
                data.append({})
                dictionary = data[-1]
                dictionary["namaProgram"] = donasi.program.DisasterName
                dictionary["jumlah"] = donasi.jumlah
        # Menunggu authentifikasinya dapat digunakan, akan menunggu
        
        return JsonResponse(data, safe=False)

daftardonasi/templates/daftardonasi.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}
    Daftar Donasi
{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/daftardonasi.css' %}">
{% endblock css %}
{% block js %}
    <script src="{% static 'javascript/daftardonasi.js' %}"></script>
    <script>
        // urldaftardonasi = "{% url 'daftardonasi:ListDonasi' %}";
    </script>
{% endblock js %}

{% block content %}
<div class="p-4">
    <div class="card">
        <div class="card-header">
            Terimakasih kami ucapkan atas donasi yang telah anda berikan!
        </div>
        <div class="card-body">
            <ul class="list-group" id="ListDonasi">
            </ul>
        </div>
    </div>
</div>

{% endblock content %}